/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forestgame;

/**
 *
 * @author Totu-vostro-5640
 */
public class MainFrame extends javax.swing.JFrame {
    private GamePanel gamePanel;
    private java.util.Map<String, String> levelPathMap = new java.util.HashMap<>();


    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
            addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent e) {
            handleExitConfirmation();
        }
    });

        initGameIntegration();
        this.setVisible(true);
        gamePanel.requestFocusInWindow();


    }
    
    private void initGameIntegration() {
        gamePanel = new GamePanel();

        gameContainerPanel.setLayout(new java.awt.BorderLayout());
        gameContainerPanel.add(gamePanel, java.awt.BorderLayout.CENTER);
        
        gamePanel.requestFocusInWindow();

        gameContainerPanel.revalidate();
        gameContainerPanel.repaint();

         levelComboBox.removeAllItems();
        levelPathMap.clear();

         levelComboBox.addItem("Level 1");
        levelComboBox.addItem("Level 2");
        levelComboBox.addItem("Level 3");
        levelComboBox.addItem("Level 4");
        levelComboBox.addItem("Level 5");
        levelComboBox.addItem("Level 6");
        levelComboBox.addItem("Level 7");
        levelComboBox.addItem("Level 8");
        levelComboBox.addItem("Level 9");
        levelComboBox.addItem("Level 10");

         levelPathMap.put("Level 1",  "levels/level1.txt");
        levelPathMap.put("Level 2",  "levels/level2.txt");
        levelPathMap.put("Level 3",  "levels/level3.txt");
        levelPathMap.put("Level 4",  "levels/level4.txt");
        levelPathMap.put("Level 5",  "levels/level5.txt");
        levelPathMap.put("Level 6",  "levels/level6.txt");
        levelPathMap.put("Level 7",  "levels/level7.txt");
        levelPathMap.put("Level 8",  "levels/level8.txt");
        levelPathMap.put("Level 9",  "levels/level9.txt");
        levelPathMap.put("Level 10", "levels/level10.txt");

         String defaultName = (String) levelComboBox.getItemAt(0);
        gamePanel.setCurrentLevelPath(levelPathMap.get(defaultName));

         levelComboBox.addActionListener(e -> {
            String name = (String) levelComboBox.getSelectedItem();
            if (name != null) {
                String path = levelPathMap.get(name);
                if (path != null) {
                    gamePanel.setCurrentLevelPath(path);
                }
            }
        });

         startGameButton.addActionListener(e -> {
            String name = (String) levelComboBox.getSelectedItem();
            if (name != null) {
                String path = levelPathMap.get(name);
                if (path != null) {
                    gamePanel.setCurrentLevelPath(path);
                }
            }
            gamePanel.startGame();
            gamePanel.requestFocusInWindow();
            

        });
        
         this.pack();


    }
     
    private void handleExitConfirmation() {
        int choice = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to exit?",
                "Confirm Exit",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE
        );

        if (choice == javax.swing.JOptionPane.YES_OPTION) {
            this.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        } else {
            this.setDefaultCloseOperation(javax.swing.JFrame.DO_NOTHING_ON_CLOSE);
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameContainerPanel = new javax.swing.JPanel();
        controlPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        levelComboBox = new javax.swing.JComboBox<>();
        startGameButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menuGame = new javax.swing.JMenu();
        menuItemNewGame = new javax.swing.JMenuItem();
        menuItemHighscores = new javax.swing.JMenuItem();
        menuItemExit = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        menuItemHowToPlay = new javax.swing.JMenuItem();
        menuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Forest Escape");
        setResizable(false);

        gameContainerPanel.setFocusable(false);
        gameContainerPanel.setMaximumSize(null);

        javax.swing.GroupLayout gameContainerPanelLayout = new javax.swing.GroupLayout(gameContainerPanel);
        gameContainerPanel.setLayout(gameContainerPanelLayout);
        gameContainerPanelLayout.setHorizontalGroup(
            gameContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        gameContainerPanelLayout.setVerticalGroup(
            gameContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 571, Short.MAX_VALUE)
        );

        controlPanel.setBackground(new java.awt.Color(230, 230, 230));

        jLabel1.setText("Level:");
        controlPanel.add(jLabel1);

        levelComboBox.setFocusable(false);
        levelComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levelComboBoxActionPerformed(evt);
            }
        });
        controlPanel.add(levelComboBox);

        startGameButton.setText("Start Game");
        startGameButton.setFocusable(false);
        startGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGameButtonActionPerformed(evt);
            }
        });
        controlPanel.add(startGameButton);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        menuGame.setText("Game");

        menuItemNewGame.setText("New Game");
        menuItemNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNewGameActionPerformed(evt);
            }
        });
        menuGame.add(menuItemNewGame);

        menuItemHighscores.setText("Highscores");
        menuItemHighscores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemHighscoresActionPerformed(evt);
            }
        });
        menuGame.add(menuItemHighscores);

        menuItemExit.setText("Exit");
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        menuGame.add(menuItemExit);

        jMenuBar1.add(menuGame);

        menuHelp.setText("Help");

        menuItemHowToPlay.setText("How to Play");
        menuItemHowToPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemHowToPlayActionPerformed(evt);
            }
        });
        menuHelp.add(menuItemHowToPlay);

        menuItemAbout.setText("About");
        menuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAboutActionPerformed(evt);
            }
        });
        menuHelp.add(menuItemAbout);

        jMenuBar1.add(menuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(controlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 932, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(gameContainerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(controlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gameContainerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void levelComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levelComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_levelComboBoxActionPerformed

    private void startGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startGameButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startGameButtonActionPerformed

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        int choice = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to exit?",
                "Confirm Exit",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE
        );

        if (choice == javax.swing.JOptionPane.YES_OPTION) {
            this.dispose();  // close the window
        }
    }//GEN-LAST:event_menuItemExitActionPerformed

    private void menuItemNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNewGameActionPerformed
        if (gamePanel != null) {
            gamePanel.startGame();
        }
    }//GEN-LAST:event_menuItemNewGameActionPerformed

    private void menuItemHighscoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemHighscoresActionPerformed
        String levelName = (String) levelComboBox.getSelectedItem();
        if (levelName == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No level selected.",
                    "Leaderboard",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        java.util.List<HighscoreEntry> scores =
                HighscoreDatabase.loadTopScores(levelName, 10);

        StringBuilder sb = new StringBuilder();
        sb.append("Leaderboard — ").append(levelName).append("\n\n");

        if (scores.isEmpty()) {
            sb.append("(No scores yet for this level)");
        } else {
            int rank = 1;
            for (HighscoreEntry e : scores) {
                sb.append(rank++).append(". ")
                  .append(e.getPlayerName())
                  .append(" — Mushrooms: ").append(e.getMushrooms())
                  .append(" | Time: ").append(e.getTimeSeconds()).append(" s")
                  .append(" | Date: ").append(e.getCreatedAt())
                  .append("\n");
            }
        }

        javax.swing.JOptionPane.showMessageDialog(this,
                sb.toString(),
                "Leaderboard",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_menuItemHighscoresActionPerformed

    private void menuItemHowToPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemHowToPlayActionPerformed
        String msg = """
            HOW TO PLAY

            • Move with W, A, S, D.
            • Avoid the wolf.
            • Collect all mushrooms.
            • Use power-ups.
            • Fog reduces visibility.
            """;
        javax.swing.JOptionPane.showMessageDialog(this, msg, "How to Play",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_menuItemHowToPlayActionPerformed

    private void menuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAboutActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this,
            "Forest Escape\nJava Swing Game\nMade in NetBeans",
            "About",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_menuItemAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

          java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controlPanel;
    private javax.swing.JPanel gameContainerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JComboBox<String> levelComboBox;
    private javax.swing.JMenu menuGame;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem menuItemAbout;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JMenuItem menuItemHighscores;
    private javax.swing.JMenuItem menuItemHowToPlay;
    private javax.swing.JMenuItem menuItemNewGame;
    private javax.swing.JButton startGameButton;
    // End of variables declaration//GEN-END:variables
}
